# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]

pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Pablo Casanova
tagline:          'Web Development, Software, Tech, Tweets, Apps'
url:              http://engineer.github.io/
shorturl:         engineer.github.io



paginate:         1

#author

author:
  name:          Pablo Casanova
  email:         isc.casanova@gmail.com
  social:        https://twitter.com/devpab
  twitter:       '@DevPab'


# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/engineer/engineer.github.io

# This is the list of pages to incldue in the header of the website.
pages_list:
  About: '/about/'
  Blog: '/blog/'
  Feed: '/atom.xml'

# Allow URL Redirects:
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
